services:
  - type: web
    name: clir
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: node server.js
    envVars:
      - key: PORT
        value: 3000
      - key: MONGO_URI
        sync: false
